import type { Metadata } from "next";
import { Inter, Spectral, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

const spectral = Spectral({
  subsets: ["latin"],

  weight: ["400", "700", "200", "300", "500", "600"],

  display: "swap",
  variable: "--font-spectral",
});
const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xelaris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={interSans.variable}>
      <body
        className={`${geistSans.variable} ${interSans.variable} ${geistMono.variable} ${spectral.variable}  antialiased bg-[#1D1F24] text-light`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
